name: todo_bloc
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.5 <3.0.0"

dependencies:
  dartz: ^0.10.0-nullsafety.2
  flutter_modular: ^4.0.0-dev.1
  flutter_bloc: ^7.3.3
  dio:
  flutter:
    sdk: flutter
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
